#!/bin/bash

# MassBank data directory (default: ./MassBank-data)
MB_DATA_DIRECTORY=${MB_DATA_DIRECTORY:=./MassBank-data}

# Database connection settings
PGUSER=${PGUSER:=postgres}
PGPASSWORD=${PGPASSWORD:=postgres}
PGDATABASE=${PGDATABASE:=postgres}
PGHOST=${PGHOST:=localhost}
PGPORT=${PGPORT:=5432}
EXPORT_API_USER=${PGUSER_EXPORT_API:=massbank_export_api_user}
EXPORT_API_PASSWORD=${PGPASSWORD_EXPORT_API:=massbank-export-api-password}
EXPORT_API_DATABASE=${PGDATABASE_EXPORT_API:=records}

PGDATABASE=$PGDATABASE psql -c "CREATE USER $PGUSER_EXPORT_API WITH ENCRYPTED PASSWORD '$PGPASSWORD_EXPORT_API';"
PGDATABASE=$PGDATABASE psql -c "CREATE DATABASE $PGDATABASE_EXPORT_API OWNER $PGUSER_EXPORT_API;"
PGUSER=$PGUSER_EXPORT_API PGPASSWORD=$PGPASSWORD_EXPORT_API PGDATABASE=$PGDATABASE_EXPORT_API psql -c "CREATE TABLE record (id SERIAL PRIMARY KEY, accession VARCHAR(50) UNIQUE NOT NULL, content TEXT NOT NULL);"