#!/bin/bash

# MassBank data directory (default: ./MassBank-data)
MB_DATA_DIRECTORY=${MB_DATA_DIRECTORY:=./MassBank-data}

# Database connection settings
PGUSER=${PGUSER:=postgres}
PGPASSWORD=${PGPASSWORD:=postgres}
PGDATABASE=${PGDATABASE:=postgres}
PGHOST=${PGHOST:=localhost}
PGPORT=${PGPORT:=5432}
EXPORT_API_USER=${PGUSER_EXPORT_API:=massbank_export_api_user}
EXPORT_API_PASSWORD=${PGPASSWORD_EXPORT_API:=massbank-export-api-password}
EXPORT_API_DATABASE=${PGDATABASE_EXPORT_API:=records}

PGDATABASE=$PGDATABASE psql -c "CREATE USER $EXPORT_API_USER WITH ENCRYPTED PASSWORD '$EXPORT_API_PASSWORD';"
PGDATABASE=$PGDATABASE psql -c "CREATE DATABASE $EXPORT_API_DATABASE OWNER $EXPORT_API_USER;"
PGUSER=$EXPORT_API_USER PGPASSWORD=$EXPORT_API_PASSWORD PGDATABASE=$EXPORT_API_DATABASE psql -c "CREATE TABLE record (id SERIAL PRIMARY KEY, accession VARCHAR(50) UNIQUE NOT NULL, content TEXT NOT NULL);"